import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#6a0f49",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  perfilContainer: {
    width: "90%",
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    marginTop: 30,
    alignSelf: "center",
  },
  header: {
    width: "100%",
    height: height * 0.12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: "5%",
    paddingTop: 30,
    backgroundColor: "#FFFFFF",
  },
  imageContainer: {
    flex: 1,
    alignItems: "center",
  },
  titleContainer: {
    flex: 2,
    alignItems: "center",
  },
  logo: {
    width: "200%",
    height: undefined,
    aspectRatio: 4,
    resizeMode: "contain",
  },
  userIcon: {
    width: 50,
    height: 50,
    resizeMode: "contain",
  },
  titleLogo: {
    width: "60%",
    height: undefined,
    aspectRatio: 2,
    resizeMode: "contain",
  },
  separator: {
    width: "100%",
    height: 4,
    backgroundColor: "#6A0F49",
  },
  cardTitle: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 10,
  },
  profileCard: {
    backgroundColor: "#FFFFFF",
    padding: 15,
    borderRadius: 15,
    alignItems: "center",
    width: "90%",
    elevation: 5,
    alignSelf: "center",
    marginTop: 15,
    marginBottom: 10,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    marginBottom: 10,
  },
  label: {
    fontSize: 16,
    fontWeight: "bold",
    color: "black",
    marginTop: 10,
  },
  info: {
    fontSize: 14,
    color: "black",
    marginBottom: 5,
  },
  buttonContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 20,
    marginBottom: 40,
    alignItems: "center",
  },
  button: {
    backgroundColor: "#c83182",
    color: "#FFF",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginHorizontal: 5,
    width: "45%",
  },
  buttonBack: {
    backgroundColor: "#c83182",
    color: "#FFF",
    borderRadius: 10,
    marginHorizontal: 5,
    fontSize: 10,
    alignSelf: "left",
    width: "30%",
  },
  logoutButton: {
    backgroundColor: "#A3003F",
  },
  buttonText: {
    color: "#FFF",
    fontSize: 12,
  },
  general: {
    backgroundColor: "#FFFFFF",
    padding: 15,
    borderRadius: 15,
    width: "90%",
    elevation: 5,
    alignSelf: "center",
    marginTop: 15,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  icon: {
    marginLeft: 10,
  },
  textContainer: {
    flex: 1,
    alignItems: "center",
  },
  generalTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "black",
  },
});
